# Generated by Django 4.0.4 on 2022-05-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0003_resturants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_category',
            field=models.CharField(max_length=30),
        ),
    ]
