# Generated by Django 4.0.4 on 2022-05-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0005_dishes_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='D_Description',
            new_name='Description',
        ),
    ]
