# Generated by Django 4.0.4 on 2022-05-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0006_rename_d_description_dishes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturants',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], max_length=5),
        ),
    ]
