# Generated by Django 4.0.4 on 2022-05-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0007_alter_resturants_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resturants',
            old_name='R_Description',
            new_name='Description',
        ),
    ]
