# Generated by Django 4.0.4 on 2022-05-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0008_rename_r_description_resturants_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='Restaurant_Dishes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Dishes.resturants'),
            preserve_default=False,
        ),
    ]
