# Generated by Django 4.0.4 on 2022-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0009_dishes_restaurant_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='size',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Trible', 'Trible')], max_length=6),
        ),
    ]
