# Generated by Django 4.0.4 on 2022-05-14 19:33

import Dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0010_alter_dishes_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='resturants',
            name='image',
            field=models.ImageField(default='', upload_to=Dishes.models.customise_image),
            preserve_default=False,
        ),
    ]
