# Generated by Django 4.0.4 on 2022-05-14 21:52

import Dishes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0011_resturants_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='image',
            field=models.ImageField(default='', upload_to=Dishes.models.customise_image),
            preserve_default=False,
        ),
    ]
