# Generated by Django 4.0.4 on 2022-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0012_dishes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='bbb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
