# Generated by Django 4.0.4 on 2022-05-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0013_bbb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='Restaurant_Dishes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='Dishes.resturants'),
        ),
    ]
