# Generated by Django 4.0.4 on 2022-05-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0014_alter_dishes_restaurant_dishes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='Restaurant_Dishes',
            new_name='Restaurant',
        ),
    ]
