# Generated by Django 4.0.4 on 2022-05-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0016_alter_dishes_restaurant_alter_dishes_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bbb',
        ),
        migrations.AddField(
            model_name='resturants',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
