# Generated by Django 4.0.4 on 2022-05-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0019_category_resturants_category_alter_resturants_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Resturants_category',
            field=models.ManyToManyField(blank=True, to='Dishes.resturants'),
        ),
    ]
