# Generated by Django 4.0.4 on 2022-05-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0021_alter_category_resturants_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='category_name',
        ),
    ]
