# Generated by Django 4.0.4 on 2022-05-28 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0022_rename_name_category_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Resturants_category',
            new_name='Resturants',
        ),
    ]
