# Generated by Django 4.0.4 on 2022-05-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0025_rename_category_name_category_name_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Resturants_category',
        ),
        migrations.AddField(
            model_name='category',
            name='Resturants',
            field=models.ManyToManyField(blank=True, related_name='Resturants_category', to='Dishes.resturants'),
        ),
    ]
