# Generated by Django 4.0.4 on 2022-05-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dishes', '0026_rename_name_category_category_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name_category',
        ),
    ]
